// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ecs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EntityDelta struct {
	_tab flatbuffers.Table
}

func GetRootAsEntityDelta(buf []byte, offset flatbuffers.UOffsetT) *EntityDelta {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EntityDelta{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsEntityDelta(buf []byte, offset flatbuffers.UOffsetT) *EntityDelta {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EntityDelta{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *EntityDelta) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EntityDelta) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EntityDelta) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EntityDelta) Bitmask() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EntityDelta) MutateBitmask(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *EntityDelta) Position(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *EntityDelta) PositionLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *EntityDelta) MutatePosition(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *EntityDelta) Orientation() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateOrientation(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *EntityDelta) Color() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EntityDelta) Shape() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EntityDelta) Size(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *EntityDelta) SizeLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *EntityDelta) MutateSize(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *EntityDelta) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EntityDelta) MaterialType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EntityDelta) Components() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EntityDelta) Volume() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateVolume(n float32) bool {
	return rcv._tab.MutateFloat32Slot(24, n)
}

func (rcv *EntityDelta) Toxicity() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateToxicity(n float32) bool {
	return rcv._tab.MutateFloat32Slot(26, n)
}

func (rcv *EntityDelta) Degradability() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *EntityDelta) MutateDegradability(n bool) bool {
	return rcv._tab.MutateBoolSlot(28, n)
}

func (rcv *EntityDelta) Fat() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateFat(n float32) bool {
	return rcv._tab.MutateFloat32Slot(30, n)
}

func (rcv *EntityDelta) Protein() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateProtein(n float32) bool {
	return rcv._tab.MutateFloat32Slot(32, n)
}

func (rcv *EntityDelta) Carbohydrate() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateCarbohydrate(n float32) bool {
	return rcv._tab.MutateFloat32Slot(34, n)
}

func (rcv *EntityDelta) WaterContent() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateWaterContent(n float32) bool {
	return rcv._tab.MutateFloat32Slot(36, n)
}

func (rcv *EntityDelta) FiberContent() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateFiberContent(n float32) bool {
	return rcv._tab.MutateFloat32Slot(38, n)
}

func (rcv *EntityDelta) Vitamins() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateVitamins(n float32) bool {
	return rcv._tab.MutateFloat32Slot(40, n)
}

func (rcv *EntityDelta) TraceElements() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateTraceElements(n float32) bool {
	return rcv._tab.MutateFloat32Slot(42, n)
}

func (rcv *EntityDelta) CaloricValue() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateCaloricValue(n float32) bool {
	return rcv._tab.MutateFloat32Slot(44, n)
}

func (rcv *EntityDelta) Hunger() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateHunger(n float32) bool {
	return rcv._tab.MutateFloat32Slot(46, n)
}

func (rcv *EntityDelta) Water() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(48))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *EntityDelta) MutateWater(n float32) bool {
	return rcv._tab.MutateFloat32Slot(48, n)
}

func EntityDeltaStart(builder *flatbuffers.Builder) {
	builder.StartObject(23)
}
func EntityDeltaAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func EntityDeltaAddBitmask(builder *flatbuffers.Builder, bitmask uint32) {
	builder.PrependUint32Slot(1, bitmask, 0)
}
func EntityDeltaAddPosition(builder *flatbuffers.Builder, position flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(position), 0)
}
func EntityDeltaStartPositionVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func EntityDeltaAddOrientation(builder *flatbuffers.Builder, orientation float32) {
	builder.PrependFloat32Slot(3, orientation, 0.0)
}
func EntityDeltaAddColor(builder *flatbuffers.Builder, color flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(color), 0)
}
func EntityDeltaAddShape(builder *flatbuffers.Builder, shape flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(shape), 0)
}
func EntityDeltaAddSize(builder *flatbuffers.Builder, size flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(size), 0)
}
func EntityDeltaStartSizeVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func EntityDeltaAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(name), 0)
}
func EntityDeltaAddMaterialType(builder *flatbuffers.Builder, materialType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(materialType), 0)
}
func EntityDeltaAddComponents(builder *flatbuffers.Builder, components flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(components), 0)
}
func EntityDeltaAddVolume(builder *flatbuffers.Builder, volume float32) {
	builder.PrependFloat32Slot(10, volume, 0.0)
}
func EntityDeltaAddToxicity(builder *flatbuffers.Builder, toxicity float32) {
	builder.PrependFloat32Slot(11, toxicity, 0.0)
}
func EntityDeltaAddDegradability(builder *flatbuffers.Builder, degradability bool) {
	builder.PrependBoolSlot(12, degradability, false)
}
func EntityDeltaAddFat(builder *flatbuffers.Builder, fat float32) {
	builder.PrependFloat32Slot(13, fat, 0.0)
}
func EntityDeltaAddProtein(builder *flatbuffers.Builder, protein float32) {
	builder.PrependFloat32Slot(14, protein, 0.0)
}
func EntityDeltaAddCarbohydrate(builder *flatbuffers.Builder, carbohydrate float32) {
	builder.PrependFloat32Slot(15, carbohydrate, 0.0)
}
func EntityDeltaAddWaterContent(builder *flatbuffers.Builder, waterContent float32) {
	builder.PrependFloat32Slot(16, waterContent, 0.0)
}
func EntityDeltaAddFiberContent(builder *flatbuffers.Builder, fiberContent float32) {
	builder.PrependFloat32Slot(17, fiberContent, 0.0)
}
func EntityDeltaAddVitamins(builder *flatbuffers.Builder, vitamins float32) {
	builder.PrependFloat32Slot(18, vitamins, 0.0)
}
func EntityDeltaAddTraceElements(builder *flatbuffers.Builder, traceElements float32) {
	builder.PrependFloat32Slot(19, traceElements, 0.0)
}
func EntityDeltaAddCaloricValue(builder *flatbuffers.Builder, caloricValue float32) {
	builder.PrependFloat32Slot(20, caloricValue, 0.0)
}
func EntityDeltaAddHunger(builder *flatbuffers.Builder, hunger float32) {
	builder.PrependFloat32Slot(21, hunger, 0.0)
}
func EntityDeltaAddWater(builder *flatbuffers.Builder, water float32) {
	builder.PrependFloat32Slot(22, water, 0.0)
}
func EntityDeltaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
