//! Bounded, request-local root retrieval outcomes and ranking metadata.

use std::fmt;

use thiserror::Error;

use super::canonical::{normalize_lookup_key, CanonicalId, LanguageTag, ReleaseId, SenseId};

/// Frozen query-side lexical encoder input contract.
pub const QUERY_LEXICAL_INPUT_VERSION: &str = "query-lexical-input-v1";
/// Frozen query-side lexical encoder identity.
pub const QUERY_LEXICAL_ENCODER_IDENTITY: &str = "transnet-lexical-bm25";
/// Frozen query-side lexical encoder revision.
pub const QUERY_LEXICAL_ENCODER_REVISION: &str = "v1";
/// Maximum number of vector nominations considered after canonical resolution.
pub const MAX_ROOT_NOMINATIONS: usize = 12;

/// A private normalized query retained only for one retrieval operation.
#[derive(Clone, PartialEq, Eq)]
pub struct RootQuery(String);

impl RootQuery {
  /// Creates one bounded, nonblank request-local query.
  ///
  /// # Errors
  ///
  /// Returns an error when the query is blank or exceeds the embedding boundary.
  pub fn new(value: impl Into<String>) -> Result<Self, RootRetrievalValidationError> {
    let value = value.into();
    if value.len() > crate::domain::model_runtime::MAX_EMBEDDING_INPUT_BYTES {
      return Err(RootRetrievalValidationError::InvalidQuery);
    }
    let value = normalize_lookup_key(&value);
    if value.is_empty() || value.len() > crate::domain::model_runtime::MAX_EMBEDDING_INPUT_BYTES {
      return Err(RootRetrievalValidationError::InvalidQuery);
    }
    Ok(Self(value))
  }

  /// Borrows the request-local value for canonical resolution or signal generation.
  pub fn as_str(&self) -> &str {
    &self.0
  }
}

impl fmt::Debug for RootQuery {
  fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    formatter.write_str("RootQuery(REDACTED)")
  }
}

/// Input accepted by bounded root retrieval.
#[derive(Clone)]
pub struct RootRetrievalRequest {
  /// Private normalized source query.
  pub query: RootQuery,
  /// Source language used by canonical resolution and projection filters.
  pub source_language: LanguageTag,
  /// Explanation language used for authoritative hydration.
  pub explanation_language: LanguageTag,
  /// Maximum number of exploratory nominations returned.
  pub limit: usize,
}

impl fmt::Debug for RootRetrievalRequest {
  fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    formatter
      .debug_struct("RootRetrievalRequest")
      .field("query", &"[redacted]")
      .field("source_language", &self.source_language)
      .field("explanation_language", &self.explanation_language)
      .field("limit", &self.limit)
      .finish()
  }
}

impl RootRetrievalRequest {
  /// Validates one request without retaining or hashing its content.
  ///
  /// # Errors
  ///
  /// Returns an error when the nomination limit is outside the closed bound.
  pub fn new(
    query: RootQuery,
    source_language: LanguageTag,
    explanation_language: LanguageTag,
    limit: usize,
  ) -> Result<Self, RootRetrievalValidationError> {
    if !(1..=MAX_ROOT_NOMINATIONS).contains(&limit) {
      return Err(RootRetrievalValidationError::InvalidLimit);
    }
    Ok(Self {
      query,
      source_language,
      explanation_language,
      limit,
    })
  }
}

/// Closed local validation failures for root retrieval.
#[derive(Clone, Copy, Debug, Error, Eq, PartialEq)]
pub enum RootRetrievalValidationError {
  /// The private query was blank or oversized.
  #[error("root retrieval query is invalid")]
  InvalidQuery,
  /// The result limit was zero or exceeded the root-retrieval bound.
  #[error("root retrieval limit is invalid")]
  InvalidLimit,
}

/// One authoritative canonical root selected before vector retrieval.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CanonicalRoot {
  /// Immutable release owning every root identity.
  pub release_id: ReleaseId,
  /// Stable projection node identity supplied by canonical-data.
  pub node_id: CanonicalId,
  /// Stable lexical sense identity resolved by canonical-data.
  pub sense_id: SenseId,
  /// Canonical display label, never generated by similarity retrieval.
  pub canonical_label: String,
}

/// Closed canonical resolution outcome evaluated before retrieval-data is contacted.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CanonicalRootResolution {
  /// No eligible canonical root exists.
  NotFound,
  /// Multiple same-precedence roots remain and must not be guessed.
  Ambiguous(Vec<CanonicalRoot>),
  /// Exactly one authoritative root may seed retrieval.
  Resolved(CanonicalRoot),
}

/// One canonical node hydrated after a projection pointer was nominated.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct HydratedRootNode {
  /// Immutable release owning the record.
  pub release_id: ReleaseId,
  /// Stable canonical projection identity.
  pub node_id: CanonicalId,
  /// Stable sense identity when this is a lexical node.
  pub sense_id: Option<SenseId>,
  /// Authority-owned display label.
  pub canonical_label: String,
}

/// Evidence class used by the root-retrieval superset.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RootEvidenceState {
  /// Canonical-data established the root identity.
  Verified,
  /// Evidence-grounded request-local synthesis; unused by similarity alone.
  Inferred,
  /// A retrieval signal nominated a hydrated canonical node without proving a fact.
  Exploratory,
}

/// One ranked item whose identity was authoritatively hydrated.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RankedRootItem {
  /// Stable canonical node identity.
  pub node_id: CanonicalId,
  /// Stable sense identity when available.
  pub sense_id: Option<SenseId>,
  /// Authority-owned label.
  pub canonical_label: String,
  /// Explicit evidence class; similarity can only produce `Exploratory`.
  pub evidence_state: RootEvidenceState,
  /// Deterministic request-local rank, starting at one.
  pub rank: usize,
  /// Integer score used only to order nominations under one release.
  pub ranking_basis_points: u16,
  /// Closed, sorted nomination mechanisms.
  pub matched_by: Vec<String>,
}

/// Retrieval coverage kept separate from canonical resolution.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RootRetrievalCoverage {
  /// All nominated pointers were hydrated under the pin.
  Complete,
  /// Some pointers were absent from canonical-data and were omitted.
  PartialPublication,
  /// Qdrant-backed retrieval was unavailable and only canonical data is returned.
  CanonicalOnly,
}

/// Result after one root-first retrieval flow.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RootRetrievalOutcome {
  /// Exact immutable release used throughout the flow.
  pub release_id: ReleaseId,
  /// Authoritative root, always present in this successful outcome.
  pub root: RankedRootItem,
  /// Evidence-grounded synthesis kept separate; this slice never creates it.
  pub inferred: Vec<RankedRootItem>,
  /// Hydrated similarity nominations that remain explicitly non-factual.
  pub exploratory: Vec<RankedRootItem>,
  /// Explicit dependency/publication coverage.
  pub coverage: RootRetrievalCoverage,
  /// Exact dense artifact version used when retrieval completed.
  pub embedding_version: Option<String>,
  /// Frozen lexical query contract used when retrieval completed.
  pub lexical_input_version: Option<&'static str>,
}

/// Top-level result preserving no-root and ambiguity without touching retrieval-data.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum RootRetrievalResult {
  /// No canonical root exists; retrieval-data was not queried.
  NotFound,
  /// Canonical ambiguity is preserved; retrieval-data was not queried.
  Ambiguous(Vec<CanonicalRoot>),
  /// One root was resolved and optionally enriched.
  Resolved(Box<RootRetrievalOutcome>),
}
