// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class EntityDelta {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntityDelta {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntityDelta(bb:flatbuffers.ByteBuffer, obj?:EntityDelta):EntityDelta {
  return (obj || new EntityDelta()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntityDelta(bb:flatbuffers.ByteBuffer, obj?:EntityDelta):EntityDelta {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntityDelta()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

bitmask():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

position(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

positionLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

positionArray():Float32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

orientation():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

color():string|null
color(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
color(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

shape():string|null
shape(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
shape(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

size(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

sizeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

sizeArray():Float32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

materialType():string|null
materialType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
materialType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

components():string|null
components(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
components(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

volume():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

toxicity():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

degradability():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

fat():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

protein():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

carbohydrate():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

waterContent():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

fiberContent():number {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

vitamins():number {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

traceElements():number {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

caloricValue():number {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

hunger():number {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

water():number {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startEntityDelta(builder:flatbuffers.Builder) {
  builder.startObject(23);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addBitmask(builder:flatbuffers.Builder, bitmask:number) {
  builder.addFieldInt32(1, bitmask, 0);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, positionOffset, 0);
}

static createPositionVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createPositionVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createPositionVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startPositionVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addOrientation(builder:flatbuffers.Builder, orientation:number) {
  builder.addFieldFloat32(3, orientation, 0.0);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, colorOffset, 0);
}

static addShape(builder:flatbuffers.Builder, shapeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, shapeOffset, 0);
}

static addSize(builder:flatbuffers.Builder, sizeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, sizeOffset, 0);
}

static createSizeVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createSizeVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createSizeVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startSizeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, nameOffset, 0);
}

static addMaterialType(builder:flatbuffers.Builder, materialTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, materialTypeOffset, 0);
}

static addComponents(builder:flatbuffers.Builder, componentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, componentsOffset, 0);
}

static addVolume(builder:flatbuffers.Builder, volume:number) {
  builder.addFieldFloat32(10, volume, 0.0);
}

static addToxicity(builder:flatbuffers.Builder, toxicity:number) {
  builder.addFieldFloat32(11, toxicity, 0.0);
}

static addDegradability(builder:flatbuffers.Builder, degradability:boolean) {
  builder.addFieldInt8(12, +degradability, +false);
}

static addFat(builder:flatbuffers.Builder, fat:number) {
  builder.addFieldFloat32(13, fat, 0.0);
}

static addProtein(builder:flatbuffers.Builder, protein:number) {
  builder.addFieldFloat32(14, protein, 0.0);
}

static addCarbohydrate(builder:flatbuffers.Builder, carbohydrate:number) {
  builder.addFieldFloat32(15, carbohydrate, 0.0);
}

static addWaterContent(builder:flatbuffers.Builder, waterContent:number) {
  builder.addFieldFloat32(16, waterContent, 0.0);
}

static addFiberContent(builder:flatbuffers.Builder, fiberContent:number) {
  builder.addFieldFloat32(17, fiberContent, 0.0);
}

static addVitamins(builder:flatbuffers.Builder, vitamins:number) {
  builder.addFieldFloat32(18, vitamins, 0.0);
}

static addTraceElements(builder:flatbuffers.Builder, traceElements:number) {
  builder.addFieldFloat32(19, traceElements, 0.0);
}

static addCaloricValue(builder:flatbuffers.Builder, caloricValue:number) {
  builder.addFieldFloat32(20, caloricValue, 0.0);
}

static addHunger(builder:flatbuffers.Builder, hunger:number) {
  builder.addFieldFloat32(21, hunger, 0.0);
}

static addWater(builder:flatbuffers.Builder, water:number) {
  builder.addFieldFloat32(22, water, 0.0);
}

static endEntityDelta(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEntityDelta(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, bitmask:number, positionOffset:flatbuffers.Offset, orientation:number, colorOffset:flatbuffers.Offset, shapeOffset:flatbuffers.Offset, sizeOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, materialTypeOffset:flatbuffers.Offset, componentsOffset:flatbuffers.Offset, volume:number, toxicity:number, degradability:boolean, fat:number, protein:number, carbohydrate:number, waterContent:number, fiberContent:number, vitamins:number, traceElements:number, caloricValue:number, hunger:number, water:number):flatbuffers.Offset {
  EntityDelta.startEntityDelta(builder);
  EntityDelta.addId(builder, idOffset);
  EntityDelta.addBitmask(builder, bitmask);
  EntityDelta.addPosition(builder, positionOffset);
  EntityDelta.addOrientation(builder, orientation);
  EntityDelta.addColor(builder, colorOffset);
  EntityDelta.addShape(builder, shapeOffset);
  EntityDelta.addSize(builder, sizeOffset);
  EntityDelta.addName(builder, nameOffset);
  EntityDelta.addMaterialType(builder, materialTypeOffset);
  EntityDelta.addComponents(builder, componentsOffset);
  EntityDelta.addVolume(builder, volume);
  EntityDelta.addToxicity(builder, toxicity);
  EntityDelta.addDegradability(builder, degradability);
  EntityDelta.addFat(builder, fat);
  EntityDelta.addProtein(builder, protein);
  EntityDelta.addCarbohydrate(builder, carbohydrate);
  EntityDelta.addWaterContent(builder, waterContent);
  EntityDelta.addFiberContent(builder, fiberContent);
  EntityDelta.addVitamins(builder, vitamins);
  EntityDelta.addTraceElements(builder, traceElements);
  EntityDelta.addCaloricValue(builder, caloricValue);
  EntityDelta.addHunger(builder, hunger);
  EntityDelta.addWater(builder, water);
  return EntityDelta.endEntityDelta(builder);
}
}
