// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { EntityDelta } from '../ecs/entity-delta';


export class Snapshot {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Snapshot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSnapshot(bb:flatbuffers.ByteBuffer, obj?:Snapshot):Snapshot {
  return (obj || new Snapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSnapshot(bb:flatbuffers.ByteBuffer, obj?:Snapshot):Snapshot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Snapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entities(index: number, obj?:EntityDelta):EntityDelta|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new EntityDelta()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

entitiesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

tick():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startSnapshot(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEntities(builder:flatbuffers.Builder, entitiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, entitiesOffset, 0);
}

static createEntitiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEntitiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTick(builder:flatbuffers.Builder, tick:bigint) {
  builder.addFieldInt64(1, tick, BigInt('0'));
}

static endSnapshot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishSnapshotBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedSnapshotBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createSnapshot(builder:flatbuffers.Builder, entitiesOffset:flatbuffers.Offset, tick:bigint):flatbuffers.Offset {
  Snapshot.startSnapshot(builder);
  Snapshot.addEntities(builder, entitiesOffset);
  Snapshot.addTick(builder, tick);
  return Snapshot.endSnapshot(builder);
}
}
