#!/usr/bin/env python3
"""Validate repository Markdown links, JSON examples, and translation structure."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import unquote, urlsplit


FENCE_PATTERN = re.compile(r"^\s*```\s*([^\s`]*)")
HEADING_PATTERN = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
LINK_PATTERN = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
HTML_LINK_PATTERN = re.compile(r"<(?:a|img)\b[^>]*?\b(?:href|src)=[\"']([^\"']+)[\"']", re.IGNORECASE)


class DuplicateKeyError(ValueError):
  """Report a duplicate object key in a JSON example."""


@dataclass(frozen=True)
class Finding:
  """Describe one validation failure at a source location."""

  path: Path
  line: int
  message: str

  def render(self, root: Path) -> str:
    """Render the finding relative to the validation root."""
    return f"{self.path.relative_to(root)}:{self.line}: {self.message}"


def reject_duplicate_keys(pairs: list[tuple[str, object]]) -> dict[str, object]:
  """Build a JSON object while rejecting repeated member names."""
  value: dict[str, object] = {}
  for key, item in pairs:
    if key in value:
      raise DuplicateKeyError(f"duplicate JSON key {key!r}")
    value[key] = item
  return value


def markdown_files(root: Path) -> list[Path]:
  """Return the hand-written Markdown files covered by repository checks."""
  files = [path for path in root.glob("*.md") if path.is_file()]
  for directory in (root / "docs", root / "docs_cn"):
    if directory.is_dir():
      files.extend(directory.rglob("*.md"))
  return sorted(set(files))


def fenced_json_findings(path: Path) -> list[Finding]:
  """Validate every fenced JSON block in one Markdown file."""
  findings: list[Finding] = []
  lines = path.read_text(encoding="utf-8").splitlines()
  fence_language: str | None = None
  fence_start = 0
  body: list[str] = []

  for line_number, line in enumerate(lines, start=1):
    match = FENCE_PATTERN.match(line)
    if match:
      if fence_language is None:
        fence_language = match.group(1).lower()
        fence_start = line_number
        body = []
      else:
        if fence_language == "json":
          try:
            json.loads("\n".join(body), object_pairs_hook=reject_duplicate_keys)
          except (json.JSONDecodeError, DuplicateKeyError) as error:
            findings.append(Finding(path, fence_start, f"invalid fenced JSON: {error}"))
        fence_language = None
      continue
    if fence_language is not None:
      body.append(line)

  if fence_language == "json":
    findings.append(Finding(path, fence_start, "unterminated fenced JSON block"))
  return findings


def github_anchors(path: Path) -> set[str]:
  """Return GitHub-style anchors generated by Markdown headings."""
  anchors: set[str] = set()
  occurrences: dict[str, int] = {}
  in_fence = False
  for line in path.read_text(encoding="utf-8").splitlines():
    if FENCE_PATTERN.match(line):
      in_fence = not in_fence
      continue
    if in_fence:
      continue
    match = HEADING_PATTERN.match(line)
    if not match:
      continue
    slug = match.group(2).strip().lower()
    slug = re.sub(r"<[^>]+>", "", slug)
    slug = re.sub(r"[^\w\- ]", "", slug, flags=re.UNICODE)
    slug = re.sub(r"\s+", "-", slug).strip("-")
    duplicate_index = occurrences.get(slug, 0)
    occurrences[slug] = duplicate_index + 1
    anchors.add(slug if duplicate_index == 0 else f"{slug}-{duplicate_index}")
  return anchors


def split_link_target(raw_target: str) -> tuple[str, str]:
  """Split a Markdown link target into its decoded path and fragment."""
  target = raw_target.strip()
  if target.startswith("<") and ">" in target:
    target = target[1 : target.index(">")]
  elif " " in target:
    target = target.split(maxsplit=1)[0]
  parsed = urlsplit(target)
  return unquote(parsed.path), unquote(parsed.fragment)


def link_findings(path: Path, root: Path) -> list[Finding]:
  """Validate relative Markdown links and their optional heading anchors."""
  findings: list[Finding] = []
  in_fence = False
  for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
    if FENCE_PATTERN.match(line):
      in_fence = not in_fence
      continue
    if in_fence:
      continue
    targets = [match.group(1) for match in LINK_PATTERN.finditer(line)]
    targets.extend(match.group(1) for match in HTML_LINK_PATTERN.finditer(line))
    for raw_target in targets:
      parsed = urlsplit(raw_target.strip("<>"))
      if parsed.scheme or parsed.netloc:
        continue
      target_path, fragment = split_link_target(raw_target)
      destination = path if not target_path else (path.parent / target_path).resolve()
      try:
        destination.relative_to(root.resolve())
      except ValueError:
        findings.append(Finding(path, line_number, f"local link escapes repository: {raw_target}"))
        continue
      if not destination.exists():
        findings.append(Finding(path, line_number, f"local link target does not exist: {raw_target}"))
        continue
      if fragment and destination.is_file() and destination.suffix.lower() == ".md":
        if fragment not in github_anchors(destination):
          findings.append(Finding(path, line_number, f"Markdown anchor does not exist: {raw_target}"))
  return findings


def heading_levels(path: Path) -> list[int]:
  """Return heading levels outside fenced blocks."""
  levels: list[int] = []
  in_fence = False
  for line in path.read_text(encoding="utf-8").splitlines():
    if FENCE_PATTERN.match(line):
      in_fence = not in_fence
      continue
    if not in_fence and (match := HEADING_PATTERN.match(line)):
      levels.append(len(match.group(1)))
  return levels


def chinese_mirror(path: Path, root: Path) -> Path | None:
  """Map an English documentation path to its required Chinese mirror."""
  if path == root / "README.md":
    return root / "README_cn.md"
  if path == root / "conventions.v1.0.1.md":
    return root / "docs_cn" / "conventions-v1.0.1_cn.md"
  docs_root = root / "docs"
  try:
    relative = path.relative_to(docs_root)
  except ValueError:
    return None
  mirror_name = f"{relative.stem}_cn{relative.suffix}"
  return root / "docs_cn" / relative.with_name(mirror_name)


def translation_findings(path: Path, root: Path) -> list[Finding]:
  """Require each English documentation page to mirror heading levels in Chinese."""
  mirror = chinese_mirror(path, root)
  if mirror is None:
    return []
  if not mirror.is_file():
    return [Finding(path, 1, f"Chinese mirror does not exist: {mirror.relative_to(root)}")]
  english_levels = heading_levels(path)
  chinese_levels = heading_levels(mirror)
  if english_levels != chinese_levels:
    return [
      Finding(
        path,
        1,
        f"heading levels differ from {mirror.relative_to(root)}: "
        f"{english_levels} != {chinese_levels}",
      )
    ]
  return []


def validate(root: Path) -> list[Finding]:
  """Run all documentation checks below the repository root."""
  root = root.resolve()
  findings: list[Finding] = []
  files = markdown_files(root)
  for path in files:
    findings.extend(fenced_json_findings(path))
    findings.extend(link_findings(path, root))
    findings.extend(translation_findings(path, root))
  return sorted(findings, key=lambda finding: (str(finding.path), finding.line, finding.message))


def main() -> int:
  """Parse command-line arguments and report documentation failures."""
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("--root", type=Path, default=Path.cwd(), help="repository root")
  arguments = parser.parse_args()
  findings = validate(arguments.root)
  for finding in findings:
    print(finding.render(arguments.root.resolve()), file=sys.stderr)
  if findings:
    print(f"documentation validation failed with {len(findings)} finding(s)", file=sys.stderr)
    return 1
  print(f"validated {len(markdown_files(arguments.root.resolve()))} Markdown files")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
